/*
 * PanelCursos.java
 *
 * Created on 20-may-2009, 18:00:50
 */
package com.codeko.apps.maimonides.cursos;

import com.codeko.apps.maimonides.DateCellEditor;
import com.codeko.apps.maimonides.MaimonidesApp;
import com.codeko.apps.maimonides.MaimonidesUtil;
import com.codeko.apps.maimonides.elementos.Curso;
import com.codeko.apps.maimonides.usr.Permisos;
import com.codeko.swing.CodekoAutoTableModel;
import com.codeko.util.Fechas;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.JTextComponent;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author Codeko
 */
public class PanelCursos extends javax.swing.JPanel {

    CodekoAutoTableModel<Curso> modelo = new CodekoAutoTableModel<Curso>(Curso.class) {

        @Override
        public void elementoModificado(Curso elemento, int col, Object valor) {
            elemento.guardar();
        }
    };
    boolean cargado = false;

    public boolean isCargado() {
        return cargado;
    }

    public void setCargado(boolean cargado) {
        this.cargado = cargado;
    }

    /** Creates new form PanelCursos */
    public PanelCursos() {
        initComponents();
        MaimonidesUtil.addMenuTabla(tabla, "Cursos");
        tabla.getColumnExt("Código").setVisible(false);
        tabla.getColumnExt("Posición").setVisible(false);
        tabla.setDefaultEditor(GregorianCalendar.class, new DateCellEditor());
        tabla.setDefaultRenderer(GregorianCalendar.class, new DefaultTableCellRenderer() {

            @Override
            public void setValue(Object val) {
                if (val instanceof GregorianCalendar) {
                    setText(Fechas.format((GregorianCalendar) val));
                } else {
                    setText("");
                }
            }
        });
        tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int pos = tabla.getSelectedRow();
                    setElementoSeleccionado(pos > -1);
                }
            }
        });

        modelo.setEditable(Permisos.edicion(getClass()));

        bNuevo.setEnabled(Permisos.creacion(getClass()));
        bNuevo.setVisible(Permisos.creacion(getClass()));

        bBorrar.setEnabled(Permisos.borrado(getClass()));
        bBorrar.setVisible(Permisos.borrado(getClass()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bActualizar = new javax.swing.JButton();
        bNuevo = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new org.jdesktop.swingx.JXTable();

        setName("Form"); // NOI18N
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getActionMap(PanelCursos.class, this);
        bActualizar.setAction(actionMap.get("actualizar")); // NOI18N
        bActualizar.setFocusable(false);
        bActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bActualizar.setName("bActualizar"); // NOI18N
        bActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bActualizar);

        bNuevo.setAction(actionMap.get("nuevo")); // NOI18N
        bNuevo.setFocusable(false);
        bNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNuevo.setName("bNuevo"); // NOI18N
        bNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bNuevo);

        bBorrar.setAction(actionMap.get("borrar")); // NOI18N
        bBorrar.setFocusable(false);
        bBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bBorrar.setName("bBorrar"); // NOI18N
        bBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bBorrar);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tabla.setModel(modelo);
        tabla.setColumnControlVisible(true);
        tabla.setName("tabla"); // NOI18N
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        if (!Beans.isDesignTime() && !isCargado()) {
            MaimonidesUtil.ejecutarTask(this, "actualizar");
        }
    }//GEN-LAST:event_formAncestorAdded

    @Action(block = Task.BlockingScope.APPLICATION)
    public Task actualizar() {
        return new ActualizarTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class ActualizarTask extends org.jdesktop.application.Task<ArrayList<Curso>, Void> {

        ActualizarTask(org.jdesktop.application.Application app) {
            super(app);
            modelo.vaciar();
            setMessage("Cargando cursos...");
            setCargado(true);
        }

        @Override
        protected ArrayList<Curso> doInBackground() {
            ArrayList<Curso> cursos = Curso.getCursos();
            return cursos;  // return your result
        }

        @Override
        protected void succeeded(ArrayList<Curso> result) {
            modelo.addDatos(result);
            setMessage("Cursos cargados correctamente.");
            setCargado(true);
            tabla.packAll();
        }
    }

    @Action(block = Task.BlockingScope.APPLICATION)
    public Task nuevo() {
        return new NuevoTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class NuevoTask extends org.jdesktop.application.Task<Curso, Void> {

        NuevoTask(org.jdesktop.application.Application app) {
            super(app);
        }

        @Override
        protected Curso doInBackground() {
            setMessage("Creando curso...");
            Curso d = new Curso(MaimonidesApp.getApplication().getAnoEscolar());
            d.setDescripcion("Nuevo curso");
            d.setCurso("");
            if (!d.guardar()) {
                d = null;
            }
            return d;
        }

        @Override
        protected void succeeded(Curso result) {
            if (result != null && result.getId() != null) {
                modelo.addDato(result);
                int row = tabla.convertRowIndexToView(modelo.indexOf(result));
                tabla.scrollRowToVisible(row);
                tabla.editCellAt(row, 0, null);
                Object cec = tabla.getEditorComponent();
                if (cec instanceof JTextComponent) {
                    ((JTextComponent) tabla.getEditorComponent()).requestFocus();
                    ((JTextComponent) tabla.getEditorComponent()).setCaretPosition(0);
                    ((JTextComponent) tabla.getEditorComponent()).selectAll();
                }
                setMessage("Curso creada correctamente.");
            } else {
                setMessage("Error creando curso.");
            }
        }
    }

    @Action(block = Task.BlockingScope.APPLICATION, enabledProperty = "elementoSeleccionado")
    public Task borrar() {
        return new BorrarTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class BorrarTask extends org.jdesktop.application.Task<ArrayList<Curso>, Void> {

        ArrayList<Curso> a = null;
        boolean borrar = false;

        BorrarTask(org.jdesktop.application.Application app) {
            super(app);
            a = getObjetosSeleccionados();

            if (a != null) {
                int op = JOptionPane.showConfirmDialog(MaimonidesApp.getApplication().getMainFrame(), "¿Esta seguro de que quiere eliminar las lineas seleccionados (" + a.size() + ")?", "Borrar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                borrar = op == JOptionPane.YES_OPTION;
            }
            firePropertyChange("setIniciado", null, true);
        }

        @Override
        protected ArrayList<Curso> doInBackground() {
            //TODO Quizás habría que verificar primero que no se está usando
            if (a != null && borrar) {
                int count = 0;
                for (Curso ae : a) {
                    setProgress(++count, 0, a.size());
                    setMessage("Borrando curso: " + ae.getDescripcion() + "...");
                    ae.borrar();
                }

                return a;
            }
            return null;
        }

        @Override
        protected void succeeded(ArrayList<Curso> result) {
            if (result != null) {
                setMessage("Cursos borradas correctamente.");
                modelo.quitarDatos(result);
            }
        }
    }

    public ArrayList<Curso> getObjetosSeleccionados() {
        int[] sels = tabla.getSelectedRows();
        ArrayList<Curso> arts = new ArrayList<Curso>(sels.length);
        for (int pos : sels) {
            if (pos > -1) {
                pos = tabla.convertRowIndexToModel(pos);
                arts.add(modelo.getElemento(pos));
            }
        }
        return arts;
    }
    private boolean elementoSeleccionado = false;

    public boolean isElementoSeleccionado() {
        return elementoSeleccionado;
    }

    public void setElementoSeleccionado(boolean b) {
        boolean old = isElementoSeleccionado();
        this.elementoSeleccionado = b;
        firePropertyChange("elementoSeleccionado", old, isElementoSeleccionado());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTable tabla;
    // End of variables declaration//GEN-END:variables
}
