/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelCBCursosGrupos.java
 *
 * Created on 02-jun-2009, 19:31:27
 */
package com.codeko.apps.maimonides.cursos;

import com.codeko.apps.maimonides.elementos.Curso;
import com.codeko.apps.maimonides.elementos.Unidad;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Codeko
 *
 */
public class PanelCBCursosGrupos extends javax.swing.JPanel {
    //TODO Este panel no se integra bien con los diseños, eliminarlo y usar los dos combos asociados
    /** Creates new form PanelCBCursosGrupos */
    public PanelCBCursosGrupos() {
        initComponents();
        if (!Beans.isDesignTime()) {
            ArrayList<Curso> cursos = Curso.getCursos();
            for (Curso c : cursos) {
                cbCurso.addItem(c);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbGrupos = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelCBCursosGrupos.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));
        cbCurso.setName("cbCurso"); // NOI18N
        cbCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCursoActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        cbGrupos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));
        cbGrupos.setName("cbGrupos"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(cbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCursoActionPerformed
        Object item = cbCurso.getSelectedItem();
        cbGrupos.removeAllItems();
        cbGrupos.addItem("Todos");
        if (item instanceof Curso) {
            Curso c = (Curso) item;
            for (Unidad u : c.getUnidades()) {
                cbGrupos.addItem(u);
            }
        }
    }//GEN-LAST:event_cbCursoActionPerformed

    public Curso getCurso() {
        return (cbCurso.getSelectedItem() instanceof Curso) ? (Curso) cbCurso.getSelectedItem() : null;
    }

    public Unidad getUnidad() {
        return (cbGrupos.getSelectedItem() instanceof Unidad) ? (Unidad) cbGrupos.getSelectedItem() : null;
    }

    public void setUnidad(Unidad u) {
        Curso c = null;
        try {
            c = Curso.getCurso(u.getIdCurso());
        } catch (Exception ex) {
            Logger.getLogger(PanelCBCursosGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbCurso.setSelectedItem(c);
        cbGrupos.setSelectedItem(u);
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        cbCurso.setEnabled(enabled);
        cbGrupos.setEnabled(enabled);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JComboBox cbGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
