/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelCursosGrupos.java
 *
 * Created on 20-may-2009, 18:07:52
 */
package com.codeko.apps.maimonides.cursos;

import com.codeko.apps.maimonides.IPanel;
import com.codeko.apps.maimonides.usr.Permisos;
import java.awt.BorderLayout;
import java.awt.Component;

/**
 *
 * @author Codeko
 */
public class PanelCursosGrupos extends javax.swing.JPanel implements IPanel {

    /** Creates new form PanelCursosGrupos */
    public PanelCursosGrupos() {
        initComponents();
        //Ahora revisamos si tenemos acceso a uno u otro panel
        if(!Permisos.acceso(panelCursos1)){
            jTabbedPane1.remove(panelCursos1);
        }

        if(!Permisos.acceso(panelGrupos1)){
            jTabbedPane1.remove(panelGrupos1);
        }

        if(jTabbedPane1.getComponentCount()==1){
            Component jc=jTabbedPane1.getComponentAt(0);
            this.removeAll();
            this.add(jc,BorderLayout.CENTER);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCursos1 = new com.codeko.apps.maimonides.cursos.PanelCursos();
        panelGrupos1 = new com.codeko.apps.maimonides.cursos.PanelGrupos();

        setName("maimonides.paneles.datos.cursos_grupos"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelCursos1.setName("panelCursos1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelCursosGrupos.class);
        jTabbedPane1.addTab(resourceMap.getString("panelCursos1.TabConstraints.tabTitle"), panelCursos1); // NOI18N

        panelGrupos1.setName("panelGrupos1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelGrupos1.TabConstraints.tabTitle"), panelGrupos1); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.codeko.apps.maimonides.cursos.PanelCursos panelCursos1;
    private com.codeko.apps.maimonides.cursos.PanelGrupos panelGrupos1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return true;
    }
}
