/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInformesPartesNoDigitalizados.java
 *
 * Created on 11-may-2010, 11:08:45
 */
package com.codeko.apps.maimonides.partes.informes;

import com.codeko.apps.maimonides.IPanel;

/**
 *
 * @author codeko
 */
public class PanelInformesPartesNoDigitalizados extends javax.swing.JPanel implements IPanel {

    /** Creates new form PanelInformesPartesNoDigitalizados */
    public PanelInformesPartesNoDigitalizados() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformesPartesNoDigitalizados = new javax.swing.JPanel();
        panelPartesNoDigitalizados = new javax.swing.JTabbedPane();
        panelPartesPendientes1 = new com.codeko.apps.maimonides.partes.informes.PanelPartesPendientes();
        panelPartesPerdidosCursos1 = new com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosCursos();
        panelPartesPerdidosUnidades1 = new com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosUnidades();
        panelPartesPerdidosPartes1 = new com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosPartes();
        panelPartesPerdidosProfesor1 = new com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosProfesor();
        panelPartesMedioDigitalizados1 = new com.codeko.apps.maimonides.partes.informes.PanelPartesMedioDigitalizados();

        setName("maimonides.paneles.faltas.informes.partes_no_digitalizados"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panelInformesPartesNoDigitalizados.setName("panelInformesPartesNoDigitalizados"); // NOI18N
        panelInformesPartesNoDigitalizados.setLayout(new java.awt.BorderLayout());

        panelPartesNoDigitalizados.setName("panelPartesNoDigitalizados"); // NOI18N

        panelPartesPendientes1.setName("panelPartesPendientes1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelInformesPartesNoDigitalizados.class);
        panelPartesNoDigitalizados.addTab(resourceMap.getString("panelPartesPendientes1.TabConstraints.tabTitle"), null, panelPartesPendientes1); // NOI18N

        panelPartesPerdidosCursos1.setName("panelPartesPerdidosCursos1"); // NOI18N
        panelPartesNoDigitalizados.addTab(resourceMap.getString("panelPartesPerdidosCursos1.TabConstraints.tabTitle"), null, panelPartesPerdidosCursos1); // NOI18N

        panelPartesPerdidosUnidades1.setName("panelPartesPerdidosUnidades1"); // NOI18N
        panelPartesNoDigitalizados.addTab(resourceMap.getString("panelPartesPerdidosUnidades1.TabConstraints.tabTitle"), null, panelPartesPerdidosUnidades1); // NOI18N

        panelPartesPerdidosPartes1.setName("panelPartesPerdidosPartes1"); // NOI18N
        panelPartesNoDigitalizados.addTab(resourceMap.getString("panelPartesPerdidosPartes1.TabConstraints.tabTitle"), null, panelPartesPerdidosPartes1); // NOI18N

        panelPartesPerdidosProfesor1.setName("panelPartesPerdidosProfesor1"); // NOI18N
        panelPartesNoDigitalizados.addTab(resourceMap.getString("panelPartesPerdidosProfesor1.TabConstraints.tabTitle"), null, panelPartesPerdidosProfesor1); // NOI18N

        panelPartesMedioDigitalizados1.setName("panelPartesMedioDigitalizados1"); // NOI18N
        panelPartesNoDigitalizados.addTab(resourceMap.getString("panelPartesMedioDigitalizados1.TabConstraints.tabTitle"), null, panelPartesMedioDigitalizados1); // NOI18N

        panelInformesPartesNoDigitalizados.add(panelPartesNoDigitalizados, java.awt.BorderLayout.CENTER);

        add(panelInformesPartesNoDigitalizados, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean puedoSusituir() {
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelInformesPartesNoDigitalizados;
    private com.codeko.apps.maimonides.partes.informes.PanelPartesMedioDigitalizados panelPartesMedioDigitalizados1;
    private javax.swing.JTabbedPane panelPartesNoDigitalizados;
    private com.codeko.apps.maimonides.partes.informes.PanelPartesPendientes panelPartesPendientes1;
    private com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosCursos panelPartesPerdidosCursos1;
    private com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosPartes panelPartesPerdidosPartes1;
    private com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosProfesor panelPartesPerdidosProfesor1;
    private com.codeko.apps.maimonides.partes.informes.PanelPartesPerdidosUnidades panelPartesPerdidosUnidades1;
    // End of variables declaration//GEN-END:variables
}
