/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelFiltroFaltas.java
 *
 * Created on 04-jun-2009, 8:35:36
 */
package com.codeko.apps.maimonides.partes.informes;

import com.codeko.apps.maimonides.elementos.ParteFaltas;
import com.codeko.apps.maimonides.partes.informes.asistencia.FiltroAsistenciaAlumno;
import com.codeko.util.Num;
import java.util.ArrayList;

/**
 *
 * @author Codeko
 */
public class PanelFiltroFaltas extends javax.swing.JPanel {

    int tipo = FiltroAsistenciaAlumno.TIPO_FALTAS;

    /** Creates new form PanelFiltroFaltas */
    public PanelFiltroFaltas() {
        initComponents();
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    public ArrayList<FiltroAsistenciaAlumno> getFiltros() {
        ArrayList<FiltroAsistenciaAlumno> filtros = new ArrayList<FiltroAsistenciaAlumno>();
        if (!tfI.getText().trim().equals("")) {
            FiltroAsistenciaAlumno f = new FiltroAsistenciaAlumno(ParteFaltas.FALTA_INJUSTIFICADA, getTipo(), cbOPI.getSelectedItem().toString(), Num.getInt(tfI.getText()));
            filtros.add(f);
        }
        if (!tfE.getText().trim().equals("")) {
            FiltroAsistenciaAlumno f = new FiltroAsistenciaAlumno(ParteFaltas.FALTA_EXPULSION, getTipo(), cbOPE.getSelectedItem().toString(), Num.getInt(tfE.getText()));
            filtros.add(f);
        }
        if (!tfJ.getText().trim().equals("")) {
            FiltroAsistenciaAlumno f = new FiltroAsistenciaAlumno(ParteFaltas.FALTA_JUSTIFICADA, getTipo(), cbOPJ.getSelectedItem().toString(), Num.getInt(tfJ.getText()));
            filtros.add(f);
        }
        if (!tfR.getText().trim().equals("")) {
            FiltroAsistenciaAlumno f = new FiltroAsistenciaAlumno(ParteFaltas.FALTA_RETRASO, getTipo(), cbOPR.getSelectedItem().toString(), Num.getInt(tfR.getText()));
            filtros.add(f);
        }
        if (!tfIR.getText().trim().equals("")) {
            FiltroAsistenciaAlumno f = new FiltroAsistenciaAlumno(ParteFaltas.FALTA_INJUSTIFICADAS_RETRASOS, getTipo(), cbOPIR.getSelectedItem().toString(), Num.getInt(tfIR.getText()));
            filtros.add(f);
        }
        return filtros;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbOPIR = new javax.swing.JComboBox();
        cbOPE = new javax.swing.JComboBox();
        cbOPR = new javax.swing.JComboBox();
        cbOPJ = new javax.swing.JComboBox();
        cbOPI = new javax.swing.JComboBox();
        tfI = new javax.swing.JTextField();
        tfJ = new javax.swing.JTextField();
        tfR = new javax.swing.JTextField();
        tfE = new javax.swing.JTextField();
        tfIR = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelFiltroFaltas.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        cbOPIR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", "<>" }));
        cbOPIR.setName("cbOPIR"); // NOI18N

        cbOPE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", "<>" }));
        cbOPE.setName("cbOPE"); // NOI18N

        cbOPR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", "<>" }));
        cbOPR.setName("cbOPR"); // NOI18N

        cbOPJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", "<>" }));
        cbOPJ.setName("cbOPJ"); // NOI18N

        cbOPI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">=", "<=", "<>" }));
        cbOPI.setName("cbOPI"); // NOI18N

        tfI.setText(resourceMap.getString("tfI.text")); // NOI18N
        tfI.setName("tfI"); // NOI18N

        tfJ.setName("tfJ"); // NOI18N

        tfR.setName("tfR"); // NOI18N

        tfE.setName("tfE"); // NOI18N

        tfIR.setName("tfIR"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbOPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOPIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfI, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfJ, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfR, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfE, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(tfIR, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbOPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbOPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbOPR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbOPE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbOPIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbOPE;
    private javax.swing.JComboBox cbOPI;
    private javax.swing.JComboBox cbOPIR;
    private javax.swing.JComboBox cbOPJ;
    private javax.swing.JComboBox cbOPR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tfE;
    private javax.swing.JTextField tfI;
    private javax.swing.JTextField tfIR;
    private javax.swing.JTextField tfJ;
    private javax.swing.JTextField tfR;
    // End of variables declaration//GEN-END:variables
}
