/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelConfiguracion.java
 *
 * Created on 26 de agosto de 2008, 12:59
 */
package com.codeko.apps.maimonides.conf;

import com.codeko.apps.maimonides.*;
import com.codeko.apps.maimonides.asistencia.ConfiguracionAsistencia;
import com.codeko.apps.maimonides.asistencia.escolaridad.ConfiguracionPerdidaEscolaridad;
import com.codeko.apps.maimonides.elementos.ParteFaltas;
import com.codeko.util.Num;
import java.beans.Beans;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author  Codeko
 */
public class PanelConfiguracionPartesAsistencia extends javax.swing.JPanel implements IPanel {

    /** Creates new form PanelConfiguracion */
    public PanelConfiguracionPartesAsistencia() {
        initComponents();
        if (!Beans.isDesignTime()) {
            MaimonidesApp.getApplication().getContext().getTaskService().execute(cargarDatos());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGuardar = new javax.swing.JButton();
        cbComprimirPartes = new javax.swing.JCheckBox();
        lTiposContabilizables = new javax.swing.JLabel();
        cbI = new javax.swing.JCheckBox();
        cbJ = new javax.swing.JCheckBox();
        cbE = new javax.swing.JCheckBox();
        cbR = new javax.swing.JCheckBox();
        lAsistenciaEnExpulsiones = new javax.swing.JLabel();
        cbAsistenciaExpulsados = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        spDiasAviso = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCartasDiaSemana = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        spCartasNumDias = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spCartasDiasInicio = new javax.swing.JSpinner();

        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getActionMap(PanelConfiguracionPartesAsistencia.class, this);
        bGuardar.setAction(actionMap.get("guardarDatos")); // NOI18N
        bGuardar.setName("bGuardar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelConfiguracionPartesAsistencia.class);
        cbComprimirPartes.setText(resourceMap.getString("cbComprimirPartes.text")); // NOI18N
        cbComprimirPartes.setName("cbComprimirPartes"); // NOI18N

        lTiposContabilizables.setText(resourceMap.getString("lTiposContabilizables.text")); // NOI18N
        lTiposContabilizables.setName("lTiposContabilizables"); // NOI18N

        cbI.setText(resourceMap.getString("cbI.text")); // NOI18N
        cbI.setName("cbI"); // NOI18N

        cbJ.setText(resourceMap.getString("cbJ.text")); // NOI18N
        cbJ.setName("cbJ"); // NOI18N

        cbE.setText(resourceMap.getString("cbE.text")); // NOI18N
        cbE.setName("cbE"); // NOI18N

        cbR.setText(resourceMap.getString("cbR.text")); // NOI18N
        cbR.setName("cbR"); // NOI18N

        lAsistenciaEnExpulsiones.setText(resourceMap.getString("lAsistenciaEnExpulsiones.text")); // NOI18N
        lAsistenciaEnExpulsiones.setName("lAsistenciaEnExpulsiones"); // NOI18N

        cbAsistenciaExpulsados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No hacer nada (dejar asistencia marcada)", "Mostrar advertencia", "Asignar expulsión", "Asignar expulsión y mostrar advertencia" }));
        cbAsistenciaExpulsados.setName("cbAsistenciaExpulsados"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        spDiasAviso.setName("spDiasAviso"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        cbCartasDiaSemana.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        cbCartasDiaSemana.setSelectedIndex(4);
        cbCartasDiaSemana.setName("cbCartasDiaSemana"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        spCartasNumDias.setName("spCartasNumDias"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        spCartasDiasInicio.setName("spCartasDiasInicio"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbComprimirPartes)
                    .addComponent(lTiposContabilizables)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbR))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbAsistenciaExpulsados, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lAsistenciaEnExpulsiones, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spDiasAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCartasDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spCartasNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spCartasDiasInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbComprimirPartes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTiposContabilizables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbI)
                    .addComponent(cbJ)
                    .addComponent(cbE)
                    .addComponent(cbR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAsistenciaEnExpulsiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAsistenciaExpulsados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spDiasAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCartasDiaSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spCartasNumDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(spCartasDiasInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JComboBox cbAsistenciaExpulsados;
    private javax.swing.JComboBox cbCartasDiaSemana;
    private javax.swing.JCheckBox cbComprimirPartes;
    private javax.swing.JCheckBox cbE;
    private javax.swing.JCheckBox cbI;
    private javax.swing.JCheckBox cbJ;
    private javax.swing.JCheckBox cbR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lAsistenciaEnExpulsiones;
    private javax.swing.JLabel lTiposContabilizables;
    private javax.swing.JSpinner spCartasDiasInicio;
    private javax.swing.JSpinner spCartasNumDias;
    private javax.swing.JSpinner spDiasAviso;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return true;
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task guardarDatos() {
        return new GuardarDatosTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class GuardarDatosTask extends org.jdesktop.application.Task<Object, Void> {

        HashMap<String, String> datos = new HashMap<String, String>();
        ArrayList<Integer> tipos = new ArrayList<Integer>();

        GuardarDatosTask(org.jdesktop.application.Application app) {
            super(app);
            try {
                spDiasAviso.commitEdit();
                spCartasNumDias.commitEdit();
                spCartasDiasInicio.commitEdit();
            } catch (ParseException ex) {
                Logger.getLogger(PanelConfiguracionPartesAsistencia.class.getName()).log(Level.SEVERE, null, ex);
            }
            datos.put("partes_asistencia.comprimir", cbComprimirPartes.isSelected() ? "1" : "0");
            datos.put("faltas_aviso_justificacion", spDiasAviso.getValue().toString());
            datos.put("cartas_faltas_dia_semana", (cbCartasDiaSemana.getSelectedIndex() + 1) + "");
            datos.put("cartas_faltas_num_dias", spCartasNumDias.getValue().toString());
            datos.put("cartas_faltas_dias_inicio", spCartasDiasInicio.getValue().toString());
            datos.put(ConfiguracionAsistencia.AAE_PARAMETRO, cbAsistenciaExpulsados.getSelectedIndex() + "");

            if (cbI.isSelected()) {
                tipos.add(ParteFaltas.FALTA_INJUSTIFICADA);
            }
            if (cbJ.isSelected()) {
                tipos.add(ParteFaltas.FALTA_JUSTIFICADA);
            }
            if (cbE.isSelected()) {
                tipos.add(ParteFaltas.FALTA_EXPULSION);
            }
            if (cbR.isSelected()) {
                tipos.add(ParteFaltas.FALTA_RETRASO);
            }
            if (tipos.isEmpty()) {
                tipos.add(-1);
            }
            setMessage("Guardando datos...");
        }

        @Override
        protected Object doInBackground() {
            Iterator it = datos.keySet().iterator();
            while (it.hasNext()) {
                String nombre = it.next().toString();
                String valor = datos.get(nombre);
                MaimonidesApp.getApplication().getConfiguracion().set(nombre, valor);
            }
            //Para los tipos de faltas usamos directamente la clase
            ConfiguracionPerdidaEscolaridad.setTipoFaltasContabilizables(tipos);
            return null;
        }

        @Override
        protected void succeeded(Object result) {
            setMessage("Datos guardados correctamente.");
        }
    }

    @Action(block = Task.BlockingScope.APPLICATION)
    public final Task cargarDatos() {
        return new CargarDatosTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class CargarDatosTask extends org.jdesktop.application.Task<Object, Void> {

        CargarDatosTask(org.jdesktop.application.Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            Configuracion cfg = MaimonidesApp.getApplication().getConfiguracion();
            cbComprimirPartes.setSelected(cfg.get("partes_asistencia.comprimir", "0").equals("1"));
            spDiasAviso.setValue(Num.getInt(cfg.get("faltas_aviso_justificacion", "100")));
            ArrayList<Integer> tipos = ConfiguracionPerdidaEscolaridad.getTiposFaltasContabilizables();
            cbI.setSelected(tipos.contains(ParteFaltas.FALTA_INJUSTIFICADA));
            cbE.setSelected(tipos.contains(ParteFaltas.FALTA_EXPULSION));
            cbR.setSelected(tipos.contains(ParteFaltas.FALTA_RETRASO));
            cbJ.setSelected(tipos.contains(ParteFaltas.FALTA_JUSTIFICADA));
            cbCartasDiaSemana.setSelectedIndex(Num.getInt(cfg.get("cartas_faltas_dia_semana", "5")) - 1);
            spCartasNumDias.setValue(Num.getInt(cfg.get("cartas_faltas_num_dias", "7")));
            spCartasDiasInicio.setValue(Num.getInt(cfg.get("cartas_faltas_dias_inicio", "11")));
            cbAsistenciaExpulsados.setSelectedIndex(Num.getInt(cfg.get(ConfiguracionAsistencia.AAE_PARAMETRO, ConfiguracionAsistencia.AAE_ASIGNAR_EXPULSION + "")));

            return null;
        }

        @Override
        protected void succeeded(Object datos) {
            setMessage("Datos cargados correctamente.");
        }
    }
}
