/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelConfiguracionPlantillas.java
 *
 * Created on 14-may-2010, 8:52:38
 */
package com.codeko.apps.maimonides.conf;

import com.codeko.apps.maimonides.MaimonidesApp;
import com.codeko.apps.maimonides.cartero.Carta;
import com.codeko.apps.maimonides.cartero.CarteroAlumno;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author codeko
 */
public class PanelConfiguracionPlantillas extends javax.swing.JPanel {

    DefaultListModel modeloSMS = new DefaultListModel();

    class Plantilla {

        String nombre = "";
        String key = "";
        String val = "";

        public String getKey() {
            return key;
        }

        public void setKey(String key) {
            this.key = key;
        }

        public String getNombre() {
            return nombre;
        }

        public void setNombre(String nombre) {
            this.nombre = nombre;
        }

        public String getVal() {
            return val;
        }

        public void setVal(String val) {
            this.val = val;
        }

        @Override
        public String toString() {
            return getNombre();
        }
    }

    /** Creates new form PanelConfiguracionPlantillas */
    public PanelConfiguracionPlantillas() {
        initComponents();
        listaPlantillas.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                setPlantillaSMSSeleccionada(listaPlantillas.getSelectedIndex() > -1);
                taPlantillaSMS.setEnabled(isPlantillaSMSSeleccionada());
                if (isPlantillaSMSSeleccionada()) {
                    taPlantillaSMS.setText(((Plantilla) listaPlantillas.getSelectedValue()).getVal());
                }
            }
        });

        Plantilla p = new Plantilla();
        p.setNombre("Faltas de asistencia");
        p.setKey("psms_aviso_faltas");
        p.setVal(MaimonidesApp.getApplication().getConfiguracion().get(p.getKey(), CarteroAlumno.getPlantillaSMS(Carta.TIPO_CARTA_AVISO_FALTAS)));
        modeloSMS.addElement(p);
        p = new Plantilla();
        p.setNombre("Expulsión");
        p.setKey("psms_expulsion");
        p.setVal(MaimonidesApp.getApplication().getConfiguracion().get(p.getKey(), CarteroAlumno.getPlantillaSMS(Carta.TIPO_CARTA_EXPULSION)));
        modeloSMS.addElement(p);
        p = new Plantilla();
        p.setNombre("Pérdida de evaluación continua");
        p.setKey("psms_escolaridad_global");
        p.setVal(MaimonidesApp.getApplication().getConfiguracion().get(p.getKey(), CarteroAlumno.getPlantillaSMS(Carta.TIPO_CARTA_PERDIDA_ESCOLARIDA_GLOBAL)));
        modeloSMS.addElement(p);
        p = new Plantilla();
        p.setNombre("Pérdida de evaluación continua materia/s");
        p.setKey("psms_escolaridad_materias");
        p.setVal(MaimonidesApp.getApplication().getConfiguracion().get(p.getKey(), CarteroAlumno.getPlantillaSMS(Carta.TIPO_CARTA_PERDIDA_ESCOLARIDA_MATERIAS)));
        modeloSMS.addElement(p);
        p = new Plantilla();
        p.setNombre("Parte de convivencia");
        p.setKey("psms_convivencia_parte");
        p.setVal(MaimonidesApp.getApplication().getConfiguracion().get(p.getKey(), CarteroAlumno.getPlantillaSMS(Carta.TIPO_CARTA_PARTE_CONVIVENCIA)));
        modeloSMS.addElement(p);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlantillas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        taPlantillaSMS = new javax.swing.JTextArea();
        bGuardarSMS = new javax.swing.JButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelConfiguracionPlantillas.class);
        jXTitledSeparator1.setTitle(resourceMap.getString("jXTitledSeparator1.title")); // NOI18N
        jXTitledSeparator1.setName("jXTitledSeparator1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listaPlantillas.setModel(modeloSMS);
        listaPlantillas.setName("listaPlantillas"); // NOI18N
        jScrollPane1.setViewportView(listaPlantillas);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        taPlantillaSMS.setColumns(20);
        taPlantillaSMS.setRows(5);
        taPlantillaSMS.setName("taPlantillaSMS"); // NOI18N
        jScrollPane2.setViewportView(taPlantillaSMS);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getActionMap(PanelConfiguracionPlantillas.class, this);
        bGuardarSMS.setAction(actionMap.get("guardarSMS")); // NOI18N
        bGuardarSMS.setName("bGuardarSMS"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                    .addComponent(bGuardarSMS, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGuardarSMS)
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action(block = Task.BlockingScope.APPLICATION, enabledProperty = "plantillaSMSSeleccionada")
    public Task guardarSMS() {
        return new GuardarSMSTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class GuardarSMSTask extends org.jdesktop.application.Task<Object, Void> {

        Plantilla p = null;

        GuardarSMSTask(org.jdesktop.application.Application app) {
            super(app);
            Object obj = listaPlantillas.getSelectedValue();
            if (obj instanceof Plantilla) {
                p = (Plantilla) obj;
                p.setVal(taPlantillaSMS.getText().trim());
            } else {
                cancel(false);
            }
        }

        @Override
        protected Object doInBackground() {

            if (p != null) {
                setMessage("Guardando plantilla...");
                MaimonidesApp.getApplication().getConfiguracion().set(p.getKey(), p.getVal());
                setMessage("Plantilla guardada.");
            }
            return null;
        }

        @Override
        protected void succeeded(Object result) {
        }
    }
    private boolean plantillaSMSSeleccionada = false;

    public boolean isPlantillaSMSSeleccionada() {
        return plantillaSMSSeleccionada;
    }

    public void setPlantillaSMSSeleccionada(boolean b) {
        boolean old = isPlantillaSMSSeleccionada();
        this.plantillaSMSSeleccionada = b;
        firePropertyChange("plantillaSMSSeleccionada", old, isPlantillaSMSSeleccionada());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarSMS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    private javax.swing.JList listaPlantillas;
    private javax.swing.JTextArea taPlantillaSMS;
    // End of variables declaration//GEN-END:variables
}
