/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelConfiguracionDatosCentro.java
 *
 * Created on 26 de agosto de 2008, 12:59
 */
package com.codeko.apps.maimonides.conf;

import com.codeko.apps.maimonides.*;
import java.beans.Beans;
import java.util.HashMap;
import java.util.Iterator;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author  Codeko
 */
public class PanelConfiguracionDatosCentro extends javax.swing.JPanel implements IPanel {

    /** Creates new form PanelConfiguracionDatosCentro */
    public PanelConfiguracionDatosCentro() {
        initComponents();
        if (!Beans.isDesignTime()) {
            MaimonidesApp.getApplication().getContext().getTaskService().execute(cargarDatos());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGuardar = new javax.swing.JButton();
        panelDatosCentro = new javax.swing.JPanel();
        lNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfDireccion = new javax.swing.JTextField();
        tfPoblacion = new javax.swing.JTextField();
        tfCP = new javax.swing.JTextField();
        tfProvincia = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfFax = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfWeb = new javax.swing.JTextField();
        cbCompatible = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfClave = new javax.swing.JPasswordField();

        setName("Form"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getActionMap(PanelConfiguracionDatosCentro.class, this);
        bGuardar.setAction(actionMap.get("guardarDatos")); // NOI18N
        bGuardar.setName("bGuardar"); // NOI18N

        panelDatosCentro.setName("panelDatosCentro"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelConfiguracionDatosCentro.class);
        lNombre.setText(resourceMap.getString("lNombre.text")); // NOI18N
        lNombre.setName("lNombre"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        tfNombre.setText(resourceMap.getString("tfNombre.text")); // NOI18N
        tfNombre.setName("tfNombre"); // NOI18N

        tfDireccion.setText(resourceMap.getString("tfDireccion.text")); // NOI18N
        tfDireccion.setName("tfDireccion"); // NOI18N

        tfPoblacion.setText(resourceMap.getString("tfPoblacion.text")); // NOI18N
        tfPoblacion.setName("tfPoblacion"); // NOI18N

        tfCP.setText(resourceMap.getString("tfCP.text")); // NOI18N
        tfCP.setName("tfCP"); // NOI18N

        tfProvincia.setText(resourceMap.getString("tfProvincia.text")); // NOI18N
        tfProvincia.setName("tfProvincia"); // NOI18N

        tfTelefono.setText(resourceMap.getString("tfTelefono.text")); // NOI18N
        tfTelefono.setName("tfTelefono"); // NOI18N

        tfFax.setText(resourceMap.getString("tfFax.text")); // NOI18N
        tfFax.setName("tfFax"); // NOI18N

        tfEmail.setText(resourceMap.getString("tfEmail.text")); // NOI18N
        tfEmail.setName("tfEmail"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        tfCodigo.setText(resourceMap.getString("tfCodigo.text")); // NOI18N
        tfCodigo.setName("tfCodigo"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        tfWeb.setText(resourceMap.getString("tfWeb.text")); // NOI18N
        tfWeb.setName("tfWeb"); // NOI18N

        cbCompatible.setText(resourceMap.getString("cbCompatible.text")); // NOI18N
        cbCompatible.setToolTipText(resourceMap.getString("cbCompatible.toolTipText")); // NOI18N
        cbCompatible.setName("cbCompatible"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        tfUsuario.setText(resourceMap.getString("tfUsuario.text")); // NOI18N
        tfUsuario.setName("tfUsuario"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        tfClave.setText(resourceMap.getString("tfClave.text")); // NOI18N
        tfClave.setName("tfClave"); // NOI18N

        javax.swing.GroupLayout panelDatosCentroLayout = new javax.swing.GroupLayout(panelDatosCentro);
        panelDatosCentro.setLayout(panelDatosCentroLayout);
        panelDatosCentroLayout.setHorizontalGroup(
            panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addGroup(panelDatosCentroLayout.createSequentialGroup()
                        .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDatosCentroLayout.createSequentialGroup()
                                .addComponent(cbCompatible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(3, 3, 3)
                                .addComponent(tfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addComponent(tfWeb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(tfFax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(tfProvincia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(tfPoblacion, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                        .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosCentroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCP, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                            .addGroup(panelDatosCentroLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfClave, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelDatosCentroLayout.setVerticalGroup(
            panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(tfCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(panelDatosCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCompatible)
                    .addComponent(jLabel10)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(543, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JCheckBox cbCompatible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lNombre;
    private javax.swing.JPanel panelDatosCentro;
    private javax.swing.JTextField tfCP;
    private javax.swing.JPasswordField tfClave;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFax;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPoblacion;
    private javax.swing.JTextField tfProvincia;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUsuario;
    private javax.swing.JTextField tfWeb;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return true;
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task guardarDatos() {
        return new GuardarDatosTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class GuardarDatosTask extends org.jdesktop.application.Task<Object, Void> {

        HashMap<String, String> datos = new HashMap<String, String>();

        GuardarDatosTask(org.jdesktop.application.Application app) {
            super(app);
            datos.put("codigo_centro", tfCodigo.getText());
            datos.put("nombre_centro", tfNombre.getText());
            datos.put("direccion_centro", tfDireccion.getText());
            datos.put("poblacion_centro", tfPoblacion.getText());
            datos.put("cp_centro", tfCP.getText());
            datos.put("provincia_centro", tfProvincia.getText());
            datos.put("telefono_centro", tfTelefono.getText());
            datos.put("fax_centro", tfFax.getText());
            datos.put("email_centro", tfEmail.getText());
            datos.put(Configuracion.CENTRO_WEB, tfWeb.getText());
            datos.put(Configuracion.CENTRO_WEB_COMPATIBLE, cbCompatible.isSelected() ? "1" : "0");
            datos.put(Configuracion.WEB_USUARIO, tfUsuario.getText());
            datos.put(Configuracion.WEB_CLAVE, new String(tfClave.getPassword()));
            setMessage("Guardando datos...");
        }

        @Override
        protected Object doInBackground() {
            Iterator it = datos.keySet().iterator();
            while (it.hasNext()) {
                String nombre = it.next().toString();
                String valor = datos.get(nombre);
                MaimonidesApp.getApplication().getConfiguracion().set(nombre, valor);
            }
            return null;  // return your result
        }

        @Override
        protected void succeeded(Object result) {
            setMessage("Datos guardados correctamente.");
        }
    }

    @Action(block = Task.BlockingScope.APPLICATION)
    public final Task cargarDatos() {
        return new CargarDatosTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class CargarDatosTask extends org.jdesktop.application.Task<HashMap<String, String>, Void> {

        CargarDatosTask(org.jdesktop.application.Application app) {
            super(app);
        }

        @Override
        protected HashMap<String, String> doInBackground() {
            //TODO Convertir estos textos a constantes y bsucar y cambiarlos por ellas
            HashMap<String, String> datos = new HashMap<String, String>();
            Configuracion cfg = MaimonidesApp.getApplication().getConfiguracion();
            datos.put("codigo_centro", cfg.get("codigo_centro", ""));
            datos.put("nombre_centro", cfg.get("nombre_centro", ""));
            datos.put("direccion_centro", cfg.get("direccion_centro", ""));
            datos.put("poblacion_centro", cfg.get("poblacion_centro", ""));
            datos.put("cp_centro", cfg.get("cp_centro", ""));
            datos.put("provincia_centro", cfg.get("provincia_centro", ""));
            datos.put("telefono_centro", cfg.get("telefono_centro", ""));
            datos.put("fax_centro", cfg.get("fax_centro", ""));
            datos.put("email_centro", cfg.get("email_centro", ""));
            datos.put(Configuracion.CENTRO_WEB, cfg.get(Configuracion.CENTRO_WEB, ""));
            datos.put(Configuracion.CENTRO_WEB_COMPATIBLE, cfg.get(Configuracion.CENTRO_WEB_COMPATIBLE, "0"));
            datos.put(Configuracion.WEB_USUARIO, cfg.get(Configuracion.WEB_USUARIO, ""));
            datos.put(Configuracion.WEB_CLAVE, cfg.get(Configuracion.WEB_CLAVE, ""));
            return datos;
        }

        @Override
        protected void succeeded(HashMap<String, String> datos) {
            tfCodigo.setText(datos.get("codigo_centro"));
            tfNombre.setText(datos.get("nombre_centro"));
            tfDireccion.setText(datos.get("direccion_centro"));
            tfPoblacion.setText(datos.get("poblacion_centro"));
            tfCP.setText(datos.get("cp_centro"));
            tfProvincia.setText(datos.get("provincia_centro"));
            tfTelefono.setText(datos.get("telefono_centro"));
            tfFax.setText(datos.get("fax_centro"));
            tfEmail.setText(datos.get("email_centro"));
            tfWeb.setText(datos.get(Configuracion.CENTRO_WEB));
            cbCompatible.setSelected(datos.get(Configuracion.CENTRO_WEB_COMPATIBLE).equals("1"));
            tfUsuario.setText(datos.get(Configuracion.WEB_USUARIO));
            tfClave.setText(datos.get(Configuracion.WEB_CLAVE));
        }
    }
}
