/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelConfiguraciones.java
 *
 * Created on 19-feb-2009, 19:13:07
 */
package com.codeko.apps.maimonides.conf;

import com.codeko.apps.maimonides.IPanel;

/**
 *
 * @author Codeko
 */
public class PanelConfiguraciones extends javax.swing.JPanel implements IPanel {

    /** Creates new form PanelConfiguraciones */
    public PanelConfiguraciones() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelConfiguracionDatosCentro1 = new com.codeko.apps.maimonides.conf.PanelConfiguracionDatosCentro();
        panelConfiguracionMail1 = new com.codeko.apps.maimonides.conf.mail.PanelConfiguracionMail("EMAIL");
        panelConfiguracionesSMS1 = new com.codeko.apps.maimonides.conf.PanelConfiguracionesSMS();
        panelConfiguracionMail3 = new com.codeko.apps.maimonides.conf.mail.PanelConfiguracionMail("VOZ");
        panelConfigSeneca1 = new com.codeko.apps.maimonides.seneca.PanelConfigSeneca();
        panelConvivencia = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelConfiguracionConvivencia1 = new com.codeko.apps.maimonides.convivencia.PanelConfiguracionConvivencia();
        panelConfiguracionExpulsiones1 = new com.codeko.apps.maimonides.convivencia.PanelConfiguracionExpulsiones();
        panelConfiguracionPartesAsistencia1 = new com.codeko.apps.maimonides.conf.PanelConfiguracionPartesAsistencia();
        panelUsuarios1 = new com.codeko.apps.maimonides.usr.PanelUsuarios();
        panelConfiguracionImpresion1 = new com.codeko.apps.maimonides.conf.PanelConfiguracionImpresion();
        panelConfiguracionPlantillas1 = new com.codeko.apps.maimonides.conf.PanelConfiguracionPlantillas();
        panelConfiguracionDigitalizacion1 = new com.codeko.apps.maimonides.conf.PanelConfiguracionDigitalizacion();
        panelConfiguracionDNIe1 = new com.codeko.apps.maimonides.dnie.config.PanelConfiguracionDNIe();
        panelConfiguracionAcceso1 = new com.codeko.apps.maimonides.usr.config.PanelConfiguracionAcceso();

        setName("Form"); // NOI18N

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelConfiguracionDatosCentro1.setName("panelConfiguracionDatosCentro1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(PanelConfiguraciones.class);
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionDatosCentro1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionDatosCentro1.TabConstraints.tabIcon"), panelConfiguracionDatosCentro1); // NOI18N

        panelConfiguracionMail1.setName("panelConfiguracionMail1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionMail1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionMail1.TabConstraints.tabIcon"), panelConfiguracionMail1); // NOI18N

        panelConfiguracionesSMS1.setName("panelConfiguracionesSMS1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionesSMS1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionesSMS1.TabConstraints.tabIcon"), panelConfiguracionesSMS1); // NOI18N

        panelConfiguracionMail3.setName("panelConfiguracionMail3"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionMail3.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionMail3.TabConstraints.tabIcon"), panelConfiguracionMail3); // NOI18N

        panelConfigSeneca1.setName("panelConfigSeneca1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfigSeneca1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfigSeneca1.TabConstraints.tabIcon"), panelConfigSeneca1); // NOI18N

        panelConvivencia.setName("panelConvivencia"); // NOI18N
        panelConvivencia.setLayout(new java.awt.BorderLayout());

        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        panelConfiguracionConvivencia1.setName("panelConfiguracionConvivencia1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("panelConfiguracionConvivencia1.TabConstraints.tabTitle"), panelConfiguracionConvivencia1); // NOI18N

        panelConfiguracionExpulsiones1.setName("panelConfiguracionExpulsiones1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("panelConfiguracionExpulsiones1.TabConstraints.tabTitle"), panelConfiguracionExpulsiones1); // NOI18N

        panelConvivencia.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(resourceMap.getString("panelConvivencia.TabConstraints.tabTitle"), resourceMap.getIcon("panelConvivencia.TabConstraints.tabIcon"), panelConvivencia); // NOI18N

        panelConfiguracionPartesAsistencia1.setName("panelConfiguracionPartesAsistencia1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionPartesAsistencia1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionPartesAsistencia1.TabConstraints.tabIcon"), panelConfiguracionPartesAsistencia1); // NOI18N

        panelUsuarios1.setName("panelUsuarios1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelUsuarios1.TabConstraints.tabTitle"), resourceMap.getIcon("panelUsuarios1.TabConstraints.tabIcon"), panelUsuarios1); // NOI18N

        panelConfiguracionImpresion1.setName("panelConfiguracionImpresion1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionImpresion1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionImpresion1.TabConstraints.tabIcon"), panelConfiguracionImpresion1); // NOI18N

        panelConfiguracionPlantillas1.setName("panelConfiguracionPlantillas1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionPlantillas1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionPlantillas1.TabConstraints.tabIcon"), panelConfiguracionPlantillas1); // NOI18N

        panelConfiguracionDigitalizacion1.setName("panelConfiguracionDigitalizacion1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionDigitalizacion1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionDigitalizacion1.TabConstraints.tabIcon"), panelConfiguracionDigitalizacion1); // NOI18N

        panelConfiguracionDNIe1.setName("panelConfiguracionDNIe1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionDNIe1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionDNIe1.TabConstraints.tabIcon"), panelConfiguracionDNIe1); // NOI18N

        panelConfiguracionAcceso1.setName("panelConfiguracionAcceso1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelConfiguracionAcceso1.TabConstraints.tabTitle"), resourceMap.getIcon("panelConfiguracionAcceso1.TabConstraints.tabIcon"), panelConfiguracionAcceso1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean puedoSusituir() {
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.codeko.apps.maimonides.seneca.PanelConfigSeneca panelConfigSeneca1;
    private com.codeko.apps.maimonides.usr.config.PanelConfiguracionAcceso panelConfiguracionAcceso1;
    private com.codeko.apps.maimonides.convivencia.PanelConfiguracionConvivencia panelConfiguracionConvivencia1;
    private com.codeko.apps.maimonides.dnie.config.PanelConfiguracionDNIe panelConfiguracionDNIe1;
    private com.codeko.apps.maimonides.conf.PanelConfiguracionDatosCentro panelConfiguracionDatosCentro1;
    private com.codeko.apps.maimonides.conf.PanelConfiguracionDigitalizacion panelConfiguracionDigitalizacion1;
    private com.codeko.apps.maimonides.convivencia.PanelConfiguracionExpulsiones panelConfiguracionExpulsiones1;
    private com.codeko.apps.maimonides.conf.PanelConfiguracionImpresion panelConfiguracionImpresion1;
    private com.codeko.apps.maimonides.conf.mail.PanelConfiguracionMail panelConfiguracionMail1;
    private com.codeko.apps.maimonides.conf.mail.PanelConfiguracionMail panelConfiguracionMail3;
    private com.codeko.apps.maimonides.conf.PanelConfiguracionPartesAsistencia panelConfiguracionPartesAsistencia1;
    private com.codeko.apps.maimonides.conf.PanelConfiguracionPlantillas panelConfiguracionPlantillas1;
    private com.codeko.apps.maimonides.conf.PanelConfiguracionesSMS panelConfiguracionesSMS1;
    private javax.swing.JPanel panelConvivencia;
    private com.codeko.apps.maimonides.usr.PanelUsuarios panelUsuarios1;
    // End of variables declaration//GEN-END:variables
}
