/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * PanelNotificacionesConvivencia.java
 *
 * Created on 02-jun-2010, 12:48:02
 */

package com.codeko.apps.maimonides.convivencia;

import com.codeko.apps.maimonides.IPanel;

/**
 *
 * @author codeko
 */
public class PanelNotificacionesConvivencia extends javax.swing.JPanel implements IPanel{

    /** Creates new form PanelNotificacionesConvivencia */
    public PanelNotificacionesConvivencia() {
        initComponents();
        panelListaPartesConvivencia1.setModoNotificaciones(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelListadoExpulsiones1 = new com.codeko.apps.maimonides.convivencia.expulsiones.PanelListadoExpulsiones();
        panelListaPartesConvivencia1 = new com.codeko.apps.maimonides.convivencia.PanelListaPartesConvivencia();

        setName("maimonides.paneles.convivencia.notificaciones_convivencia"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelListadoExpulsiones1.setName("panelListadoExpulsiones1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelNotificacionesConvivencia.class);
        jTabbedPane1.addTab(resourceMap.getString("panelListadoExpulsiones1.TabConstraints.tabTitle"), resourceMap.getIcon("panelListadoExpulsiones1.TabConstraints.tabIcon"), panelListadoExpulsiones1); // NOI18N

        panelListaPartesConvivencia1.setName("panelListaPartesConvivencia1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelListaPartesConvivencia1.TabConstraints.tabTitle"), resourceMap.getIcon("panelListaPartesConvivencia1.TabConstraints.tabIcon"), panelListaPartesConvivencia1); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean puedoSusituir() {
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.codeko.apps.maimonides.convivencia.PanelListaPartesConvivencia panelListaPartesConvivencia1;
    private com.codeko.apps.maimonides.convivencia.expulsiones.PanelListadoExpulsiones panelListadoExpulsiones1;
    // End of variables declaration//GEN-END:variables

}
