/*
 * PanelCartas.java
 *
 * Created on 31-ago-2009, 10:36:19
 */

package com.codeko.apps.maimonides.partes.cartas;

import com.codeko.apps.maimonides.IPanel;

/**
 *
 * @author Codeko
 */
public class PanelCartas extends javax.swing.JPanel implements IPanel {

    /** Creates new form PanelCartas */
    public PanelCartas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCartasAsistencia1 = new com.codeko.apps.maimonides.partes.cartas.PanelCartasAsistencia();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelCartasEscolaridad1 = new com.codeko.apps.maimonides.partes.cartas.PanelCartasEscolaridad();
        panelCartasEscolaridadMaterias1 = new com.codeko.apps.maimonides.partes.cartas.PanelCartasEscolaridadMaterias();

        setName("maimonides.paneles.faltas.cartas"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelCartasAsistencia1.setName("panelCartasAsistencia1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelCartas.class);
        jTabbedPane1.addTab(resourceMap.getString("panelCartasAsistencia1.TabConstraints.tabTitle"), panelCartasAsistencia1); // NOI18N

        jTabbedPane2.setName("jTabbedPane2"); // NOI18N

        panelCartasEscolaridad1.setName("panelCartasEscolaridad1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("panelCartasEscolaridad1.TabConstraints.tabTitle"), panelCartasEscolaridad1); // NOI18N

        panelCartasEscolaridadMaterias1.setName("panelCartasEscolaridadMaterias1"); // NOI18N
        jTabbedPane2.addTab(resourceMap.getString("panelCartasEscolaridadMaterias1.TabConstraints.tabTitle"), panelCartasEscolaridadMaterias1); // NOI18N

        jTabbedPane1.addTab(resourceMap.getString("jTabbedPane2.TabConstraints.tabTitle"), jTabbedPane2); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.codeko.apps.maimonides.partes.cartas.PanelCartasAsistencia panelCartasAsistencia1;
    private com.codeko.apps.maimonides.partes.cartas.PanelCartasEscolaridad panelCartasEscolaridad1;
    private com.codeko.apps.maimonides.partes.cartas.PanelCartasEscolaridadMaterias panelCartasEscolaridadMaterias1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return true;
    }

}
