/*
 * LeyendaPartes.java
 *
 * Created on 20 de octubre de 2008, 10:49
 */

package com.codeko.apps.maimonides.partes;

import com.codeko.apps.maimonides.elementos.ParteFaltas;

/**
 *
 * @author  Codeko
 */
public class LeyendaPartes extends javax.swing.JPanel {

    /** Creates new form LeyendaPartes */
    public LeyendaPartes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lInfoVacion = new javax.swing.JLabel();
        lInfoVacion1 = new javax.swing.JLabel();
        lInfoVacion3 = new javax.swing.JLabel();
        lInfoVacion2 = new javax.swing.JLabel();
        lInfoVacion4 = new javax.swing.JLabel();
        lInfoVacion5 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        lInfoVacion.setBackground(ParteFaltas.getColorTipoFalta(""));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(LeyendaPartes.class);
        lInfoVacion.setText(resourceMap.getString("lInfoVacion.text")); // NOI18N
        lInfoVacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lInfoVacion.setName("lInfoVacion"); // NOI18N
        lInfoVacion.setOpaque(true);

        lInfoVacion1.setBackground(ParteFaltas.getColorTipoFalta("A"));
        lInfoVacion1.setText(resourceMap.getString("lInfoVacion1.text")); // NOI18N
        lInfoVacion1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lInfoVacion1.setName("lInfoVacion1"); // NOI18N
        lInfoVacion1.setOpaque(true);

        lInfoVacion3.setBackground(ParteFaltas.getColorTipoFalta("J"));
        lInfoVacion3.setText(resourceMap.getString("lInfoVacion3.text")); // NOI18N
        lInfoVacion3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lInfoVacion3.setName("lInfoVacion3"); // NOI18N
        lInfoVacion3.setOpaque(true);

        lInfoVacion2.setBackground(ParteFaltas.getColorTipoFalta("I"));
        lInfoVacion2.setText(resourceMap.getString("lInfoVacion2.text")); // NOI18N
        lInfoVacion2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lInfoVacion2.setName("lInfoVacion2"); // NOI18N
        lInfoVacion2.setOpaque(true);

        lInfoVacion4.setBackground(ParteFaltas.getColorTipoFalta("R"));
        lInfoVacion4.setText(resourceMap.getString("lInfoVacion4.text")); // NOI18N
        lInfoVacion4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lInfoVacion4.setName("lInfoVacion4"); // NOI18N
        lInfoVacion4.setOpaque(true);

        lInfoVacion5.setBackground(ParteFaltas.getColorTipoFalta("E"));
        lInfoVacion5.setText(resourceMap.getString("lInfoVacion5.text")); // NOI18N
        lInfoVacion5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lInfoVacion5.setName("lInfoVacion5"); // NOI18N
        lInfoVacion5.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lInfoVacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lInfoVacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lInfoVacion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lInfoVacion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lInfoVacion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lInfoVacion5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lInfoVacion)
                    .addComponent(lInfoVacion3)
                    .addComponent(lInfoVacion4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lInfoVacion1)
                    .addComponent(lInfoVacion2)
                    .addComponent(lInfoVacion5)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lInfoVacion;
    private javax.swing.JLabel lInfoVacion1;
    private javax.swing.JLabel lInfoVacion2;
    private javax.swing.JLabel lInfoVacion3;
    private javax.swing.JLabel lInfoVacion4;
    private javax.swing.JLabel lInfoVacion5;
    // End of variables declaration//GEN-END:variables

}
