/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelVisorPartes.java
 *
 * Created on 29-abr-2009, 12:07:55
 */

package com.codeko.apps.maimonides.partes;

/**
 *
 * @author Codeko
 */
public class PanelVisorPartes extends javax.swing.JPanel {

    /** Creates new form PanelVisorPartes */
    public PanelVisorPartes() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        panelListaAlumnosParte1 = new com.codeko.apps.maimonides.partes.PanelListaAlumnosParte();
        visorImagenes1 = new com.codeko.apps.maimonides.digitalizacion.VisorImagenes();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        split.setName("split"); // NOI18N

        panelListaAlumnosParte1.setName("panelListaAlumnosParte1"); // NOI18N
        split.setLeftComponent(panelListaAlumnosParte1);

        visorImagenes1.setName("visorImagenes1"); // NOI18N
        split.setRightComponent(visorImagenes1);

        add(split, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.codeko.apps.maimonides.partes.PanelListaAlumnosParte panelListaAlumnosParte1;
    private javax.swing.JSplitPane split;
    private com.codeko.apps.maimonides.digitalizacion.VisorImagenes visorImagenes1;
    // End of variables declaration//GEN-END:variables

}
