/*
 * PanelMensajesActualizacion.java
 *
 * Created on 18-jun-2010, 20:43:59
 */
package com.codeko.apps.maimonides.mantenimiento;

import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JLabel;

/**
 *
 * @author codeko
 */
public class PanelMensajesActualizacion extends javax.swing.JPanel {

    /** Creates new form PanelMensajesActualizacion */
    public PanelMensajesActualizacion() {
        initComponents();
    }

    public void setMensajes(ArrayList<String> mensajes) {
        panelNotificaciones.removeAll();
        GroupLayout panelNotificacionesLayout = (GroupLayout) panelNotificaciones.getLayout();
        for (String s : mensajes) {
            JLabel l = new JLabel(s);
            panelNotificacionesLayout.setHorizontalGroup(
                    panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(panelNotificacionesLayout.createSequentialGroup().addContainerGap().addComponent(l, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE).addContainerGap()));
            panelNotificacionesLayout.setVerticalGroup(
                    panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(panelNotificacionesLayout.createSequentialGroup().addContainerGap().addComponent(l).addContainerGap(332, Short.MAX_VALUE)));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelNotificaciones = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelMensajesActualizacion.class);
        panelNotificaciones.setBackground(resourceMap.getColor("panelNotificaciones.background")); // NOI18N
        panelNotificaciones.setName("panelNotificaciones"); // NOI18N

        javax.swing.GroupLayout panelNotificacionesLayout = new javax.swing.GroupLayout(panelNotificaciones);
        panelNotificaciones.setLayout(panelNotificacionesLayout);
        panelNotificacionesLayout.setHorizontalGroup(
            panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        panelNotificacionesLayout.setVerticalGroup(
            panelNotificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelNotificaciones);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelNotificaciones;
    // End of variables declaration//GEN-END:variables
}
