/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/

package com.codeko.apps.maimonides.alumnos;

import com.codeko.apps.maimonides.IPanel;
import com.codeko.apps.maimonides.convivencia.PanelPestanaConvivencia;
import com.codeko.apps.maimonides.elementos.Alumno;
import com.codeko.util.CTiempo;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

public class PanelAlumnos2 extends javax.swing.JPanel implements IPanel {

    PanelPestanaConvivencia panelConvivencia = null;
    PanelFichaAlumno panelFichaAlumno = null;
    PanelAlumnos panelAlumnos = null;

    public PanelAlumnos2() {
        CTiempo t = new CTiempo("P AL");
        panelFichaAlumno = new PanelFichaAlumno();
        panelFichaAlumno.addPropertyChangeListener(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent pce) {
                if ("vaciar".equals(pce.getPropertyName())) {
                    if (panelConvivencia != null) {
                        panelConvivencia.vaciar();
                    }
                } else if ("alumno".equals(pce.getPropertyName())) {
                    if (panelConvivencia != null) {
                        panelConvivencia.setAlumno((Alumno) pce.getNewValue());
                        if(pestanas.getSelectedComponent()==panelConvivencia){
                            panelConvivencia.cargar();
                        }
                    }
                } else if ("guardado".equals(pce.getPropertyName())) {
                    if (panelConvivencia != null) {
                        panelConvivencia.cargar();
                    }
                } else if ("mostrarConvivencia".equals(pce.getPropertyName())) {
                    boolean mostrar = (Boolean) pce.getNewValue();
                    if (mostrar) {
                        getPanelConvivencia().setAlumno(panelFichaAlumno.getAlumno());
                        pestanas.addTab("Convivencia", getPanelConvivencia());
                        pestanas.setSelectedComponent(getPanelConvivencia());
                    } else {
                        pestanas.remove(getPanelConvivencia());
                    }
                }
            }
        });
        t.showTimer("ficha");
        panelAlumnos = new com.codeko.apps.maimonides.alumnos.PanelAlumnos();
        t.showTimer("listado");
        initComponents();
        pestanas.addTab("Ficha", panelFichaAlumno);

        pestanas.addTab("Listado", panelAlumnos);
    }

    private PanelPestanaConvivencia getPanelConvivencia() {
        if (panelConvivencia == null) {
            panelConvivencia = new PanelPestanaConvivencia();
        }
        return panelConvivencia;
    }

    public void mostrarAlumno(Alumno a) {
        panelFichaAlumno.setAlumno(a);
        pestanas.setSelectedComponent(panelFichaAlumno);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestanas = new javax.swing.JTabbedPane();

        setName("maimonides.paneles.datos.alumnos"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        pestanas.setName("pestanas"); // NOI18N
        add(pestanas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane pestanas;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return panelFichaAlumno.puedoSusituir() && panelAlumnos.puedoSusituir();
    }
}
