/*
 * PanelTutor.java
 *
 * Created on 31-mar-2009, 11:04:30
 */
package com.codeko.apps.maimonides.alumnos;

import com.codeko.apps.maimonides.elementos.Tutor;

/**
 *
 * @author Codeko
 */
public class PanelTutor extends javax.swing.JPanel {

    Tutor tutor = null;

    /** Creates new form PanelTutor */
    public PanelTutor() {
        initComponents();
    }

    public Tutor getTutor() {
        if (tutor != null) {
            tutor.setNombre(tfNombre.getText());
            tutor.setApellido1(tfApellido1.getText());
            tutor.setApellido2(tfApellido2.getText());
            tutor.setDni(tfDni.getText());
            tutor.setSexo(cbSexo.getSelectedIndex() == 0 ? "H" : "M");
        }
        return tutor;
    }

    public void setTutor(Tutor tutor) {
        this.tutor = tutor;
        if (tutor != null) {
            tfNombre.setText(tutor.getNombre());
            tfApellido1.setText(tutor.getApellido1());
            tfApellido2.setText(tutor.getApellido2());
            tfDni.setText(tutor.getDni());
            cbSexo.setSelectedIndex(tutor.getSexo().equals("M") ? 1 : 0);
        } else {
            tfNombre.setText("");
            tfApellido1.setText("");
            tfApellido2.setText("");
            tfDni.setText("");
            cbSexo.setSelectedIndex(0);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido1 = new javax.swing.JTextField();
        tfApellido2 = new javax.swing.JTextField();
        lDni = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        lSexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        lNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelTutor.class);
        lNombre.setText(resourceMap.getString("lNombre.text")); // NOI18N
        lNombre.setName("lNombre"); // NOI18N

        tfNombre.setText(resourceMap.getString("tfNombre.text")); // NOI18N
        tfNombre.setName("tfNombre"); // NOI18N

        tfApellido1.setText(resourceMap.getString("tfApellido1.text")); // NOI18N
        tfApellido1.setName("tfApellido1"); // NOI18N

        tfApellido2.setText(resourceMap.getString("tfApellido2.text")); // NOI18N
        tfApellido2.setName("tfApellido2"); // NOI18N

        lDni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lDni.setText(resourceMap.getString("lDni.text")); // NOI18N
        lDni.setName("lDni"); // NOI18N

        tfDni.setText(resourceMap.getString("tfDni.text")); // NOI18N
        tfDni.setName("tfDni"); // NOI18N

        lSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lSexo.setText(resourceMap.getString("lSexo.text")); // NOI18N
        lSexo.setName("lSexo"); // NOI18N

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));
        cbSexo.setName("cbSexo"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lDni)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDni, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(lSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(cbSexo, 0, 85, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDni)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSexo)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JLabel lDni;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lSexo;
    private javax.swing.JTextField tfApellido1;
    private javax.swing.JTextField tfApellido2;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
