/*
 * PanelEnvioEmail.java
 *
 * Created on 17-feb-2009, 19:02:08
 */
package com.codeko.apps.maimonides.alumnos;

import com.codeko.apps.maimonides.MaimonidesApp;
import com.codeko.apps.maimonides.cartero.CarteroAlumno;
import com.codeko.apps.maimonides.conf.mail.ConfiguracionMail;
import com.codeko.apps.maimonides.elementos.IEmailable;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.validator.EmailValidator;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author Codeko
 */
public class PanelEnvioEmail extends javax.swing.JPanel {

    IEmailable destinatario = null;
    ConfiguracionMail conf = new ConfiguracionMail("EMAIL");

    public PanelEnvioEmail() {
        initComponents();
        setDestinatario(null);
    }

    public IEmailable getDestinatario() {
        return destinatario;
    }

    public final void setDestinatario(IEmailable destinatario) {
        this.destinatario = destinatario;
        boolean valid = false;
        String email = "";
        if (destinatario != null) {
            email = getDestinatario().getEmail();
        }
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelEnvioEmail.class);
        lTitulo.setText(resourceMap.getString("lTitulo.text", email)); // NOI18N
        valid = EmailValidator.getInstance().isValid(email);
        lTitulo.setForeground(valid ? Color.black : Color.red);
        setNumeroValido(valid);
    }

    public int getMaxCaracteres() {
        return conf.getMaximoCaracteres();
    }

    @Action(block = Task.BlockingScope.ACTION, enabledProperty = "numeroValido")
    public Task enviar() {
        return new EnviarTask(org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class));
    }

    private class EnviarTask extends org.jdesktop.application.Task<Boolean, Void> {

        EnviarTask(org.jdesktop.application.Application app) {
            super(app);
            setMessage("Enviando email a " + getDestinatario().getEmail());
        }

        @Override
        protected Boolean doInBackground() {
            setMessage("Enviando email a " + getDestinatario().getEmail());
            try {
                ArrayList<IEmailable> dest = new ArrayList<IEmailable>();
                dest.add(getDestinatario());
                if (CarteroAlumno.enviarEmail(tfAsunto.getText(), taTexto.getText() + conf.getPie(), null, dest)) {
                    setMessage("Email enviado correctamente");
                    return true;
                }
            } catch (Exception ex) {
                Logger.getLogger(PanelEnvioEmail.class.getName()).log(Level.SEVERE, null, ex);
                setMessage("Se ha producido un error enviado el email: " + ex.getLocalizedMessage());
            }
            return false;
        }

        @Override
        protected void succeeded(Boolean result) {
            if (result) {
                JOptionPane.showMessageDialog(MaimonidesApp.getMaimonidesView().getFrame(), "Email enviado correctamente", "Email enviado correctamente", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(MaimonidesApp.getMaimonidesView().getFrame(), "Error enviando email", "Error enviando email", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTexto = new javax.swing.JTextArea();
        bEnviar = new javax.swing.JButton();
        lAsunto = new javax.swing.JLabel();
        tfAsunto = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelEnvioEmail.class);
        lTitulo.setText(resourceMap.getString("lTitulo.text")); // NOI18N
        lTitulo.setName("lTitulo"); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taTexto.setColumns(20);
        taTexto.setLineWrap(true);
        taTexto.setRows(5);
        taTexto.setWrapStyleWord(true);
        taTexto.setName("taTexto"); // NOI18N
        jScrollPane1.setViewportView(taTexto);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getActionMap(PanelEnvioEmail.class, this);
        bEnviar.setAction(actionMap.get("enviar")); // NOI18N
        bEnviar.setText(resourceMap.getString("bEnviar.text")); // NOI18N
        bEnviar.setName("bEnviar"); // NOI18N

        lAsunto.setText(resourceMap.getString("lAsunto.text")); // NOI18N
        lAsunto.setName("lAsunto"); // NOI18N

        tfAsunto.setText(resourceMap.getString("tfAsunto.text")); // NOI18N
        tfAsunto.setName("tfAsunto"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lAsunto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                    .addComponent(bEnviar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAsunto)
                    .addComponent(tfAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEnviar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean numeroValido = false;

    public boolean isNumeroValido() {
        return numeroValido;
    }

    public void setNumeroValido(boolean b) {
        boolean old = isNumeroValido();
        this.numeroValido = b;
        firePropertyChange("numeroValido", old, isNumeroValido());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAsunto;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextArea taTexto;
    private javax.swing.JTextField tfAsunto;
    // End of variables declaration//GEN-END:variables
}
