/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/

package com.codeko.apps.maimonides.alumnos;

import com.codeko.apps.maimonides.IPanel;

public class PanelControlAlumnos extends javax.swing.JPanel implements IPanel{

    public PanelControlAlumnos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAlumnosBorrados1 = new com.codeko.apps.maimonides.alumnos.PanelAlumnosBorrados();
        panelAlumnosSinUnidad1 = new com.codeko.apps.maimonides.alumnos.PanelAlumnosSinUnidad();

        setName("maimonides.paneles.herramientas.control_datos_alumnos"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        panelAlumnosBorrados1.setName("panelAlumnosBorrados1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelControlAlumnos.class);
        jTabbedPane1.addTab(resourceMap.getString("panelAlumnosBorrados1.TabConstraints.tabTitle"), resourceMap.getIcon("panelAlumnosBorrados1.TabConstraints.tabIcon"), panelAlumnosBorrados1, resourceMap.getString("panelAlumnosBorrados1.TabConstraints.tabToolTip")); // NOI18N

        panelAlumnosSinUnidad1.setName("panelAlumnosSinUnidad1"); // NOI18N
        jTabbedPane1.addTab(resourceMap.getString("panelAlumnosSinUnidad1.TabConstraints.tabTitle"), resourceMap.getIcon("panelAlumnosSinUnidad1.TabConstraints.tabIcon"), panelAlumnosSinUnidad1); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.codeko.apps.maimonides.alumnos.PanelAlumnosBorrados panelAlumnosBorrados1;
    private com.codeko.apps.maimonides.alumnos.PanelAlumnosSinUnidad panelAlumnosSinUnidad1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return true;
    }

}
