/*
 * PanelArbolErrores.java
 *
 * Created on 12 de agosto de 2008, 14:12
 */

package com.codeko.apps.maimonides.importadores;

import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author  Codeko
 */
public class PanelArbolErrores extends javax.swing.JPanel {
    DefaultMutableTreeNode nodoBase=null;

    public DefaultMutableTreeNode getNodoBase() {
        return nodoBase;
    }

    public final void setNodoBase(DefaultMutableTreeNode nodoBase) {
        this.nodoBase = nodoBase;
    }
    
    /** Creates new form PanelArbolErrores */
    public PanelArbolErrores(DefaultMutableTreeNode nodoBase,String mensaje) {
        setNodoBase(nodoBase);
        initComponents();
        lMensaje.setText(mensaje);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree(getNodoBase());
        lMensaje = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        arbol.setName("arbol"); // NOI18N
        jScrollPane1.setViewportView(arbol);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.codeko.apps.maimonides.MaimonidesApp.class).getContext().getResourceMap(PanelArbolErrores.class);
        lMensaje.setText(resourceMap.getString("lMensaje.text")); // NOI18N
        lMensaje.setName("lMensaje"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lMensaje;
    // End of variables declaration//GEN-END:variables

}
