/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
 **/
/*
 * PanelConfgiracionDNIe.java
 *
 * Created on 12-sep-2011, 14:30:29
 */
package com.codeko.apps.maimonides.dnie.config;

import com.codeko.apps.maimonides.IPanel;
import com.codeko.apps.maimonides.MaimonidesUtil;
import com.codeko.apps.maimonides.dnie.Configuracion;
import com.codeko.util.Str;
import com.codeko.util.estructuras.Par;
import javax.swing.SwingUtilities;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;

/**
 *
 * @author Codeko <codeko@codeko.com>
 */
public class PanelConfiguracionDNIe extends javax.swing.JPanel implements IPanel {

    public boolean loaded = false;

    /** Creates new form PanelConfgiracionDNIe */
    public PanelConfiguracionDNIe() {
        initComponents();
        Par<String, String> a = new Par<String, String>("Ruta automática", "") {

            @Override
            public String toString() {
                return Str.noNulo(getA());
            }
        };
        cbRutaOpenSC.addItem(a);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lSepConfigLibs = new org.jdesktop.swingx.JXTitledSeparator();
        cbRutaOpenSC = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jXTitledSeparator1 = new org.jdesktop.swingx.JXTitledSeparator();
        cbDNIeGlobal = new javax.swing.JCheckBox();
        cbDNIeLocal = new javax.swing.JCheckBox();
        jXTitledSeparator2 = new org.jdesktop.swingx.JXTitledSeparator();
        cbSolicitarClave = new javax.swing.JComboBox();
        bGuardar = new javax.swing.JButton();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lSepConfigLibs.setTitle("Bibliotecas de acceso a DNIe");
        lSepConfigLibs.setName("lSepConfigLibs"); // NOI18N

        cbRutaOpenSC.setEditable(true);
        cbRutaOpenSC.setName("cbRutaOpenSC"); // NOI18N

        jLabel1.setText("Ruta a OpenSC-OpenDNIe");
        jLabel1.setName("jLabel1"); // NOI18N

        jXTitledSeparator1.setTitle("Activación de DNIe");
        jXTitledSeparator1.setName("jXTitledSeparator1"); // NOI18N

        cbDNIeGlobal.setText("Acceso con DNIe activado globalmente");
        cbDNIeGlobal.setName("cbDNIeGlobal"); // NOI18N

        cbDNIeLocal.setText("Acceso con DNIe activado en este equipo");
        cbDNIeLocal.setName("cbDNIeLocal"); // NOI18N

        jXTitledSeparator2.setTitle("Solicitar clave de DNIe");
        jXTitledSeparator2.setName("jXTitledSeparator2"); // NOI18N

        cbSolicitarClave.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solicitar clave siempre", "Solicitar sólo para usuarios externos (Alumnos/Padres)" }));
        cbSolicitarClave.setName("cbSolicitarClave"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(PanelConfiguracionDNIe.class, this);
        bGuardar.setAction(actionMap.get("guardar")); // NOI18N
        bGuardar.setName("bGuardar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbRutaOpenSC, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lSepConfigLibs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(cbDNIeGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(cbDNIeLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbSolicitarClave, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jXTitledSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
                    .addComponent(bGuardar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSepConfigLibs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRutaOpenSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXTitledSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDNIeGlobal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDNIeLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXTitledSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSolicitarClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(bGuardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
    if (!loaded) {
        loaded = true;
        MaimonidesUtil.ejecutarTask(this, "loadData");
    }
}//GEN-LAST:event_formAncestorAdded
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JCheckBox cbDNIeGlobal;
    private javax.swing.JCheckBox cbDNIeLocal;
    private javax.swing.JComboBox cbRutaOpenSC;
    private javax.swing.JComboBox cbSolicitarClave;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator1;
    private org.jdesktop.swingx.JXTitledSeparator jXTitledSeparator2;
    private org.jdesktop.swingx.JXTitledSeparator lSepConfigLibs;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean puedoSusituir() {
        return true;
    }

    @Action
    public Task<Object, Void> loadData() {
        return new LoadDataTask(org.jdesktop.application.Application.getInstance());
    }

    private class LoadDataTask extends org.jdesktop.application.Task<Object, Void> {

        LoadDataTask(org.jdesktop.application.Application app) {
            super(app);
        }

        @Override
        protected Object doInBackground() {
            final String openSCPath = Configuracion.getOpenSCPath();
            final boolean dniEnabled = Configuracion.isLocalDNIeAccessEnabled();
            final boolean globalDniEnabled = Configuracion.isGlobalDNIeAccessEnabled();
            final int accesPolicy = Configuracion.getDNIePassPolicy();
            SwingUtilities.invokeLater(new Runnable() {

                @Override
                public void run() {
                    if (!openSCPath.equals("")) {
                        Par<String, String> a = new Par<String, String>(openSCPath, openSCPath) {

                            @Override
                            public String toString() {
                                return Str.noNulo(getA());
                            }
                        };
                        cbRutaOpenSC.addItem(a);
                        cbRutaOpenSC.setSelectedItem(a);
                    }
                    cbDNIeGlobal.setSelected(globalDniEnabled);
                    cbDNIeLocal.setSelected(dniEnabled);
                    cbSolicitarClave.setSelectedIndex(accesPolicy);
                }
            });
            return null;
        }

        @Override
        protected void succeeded(Object result) {
        }
    }

    @Action(block = Task.BlockingScope.ACTION)
    public Task<Object, Void> guardar() {
        return new GuardarTask(org.jdesktop.application.Application.getInstance());
    }

    private class GuardarTask extends org.jdesktop.application.Task<Object, Void> {

        GuardarTask(org.jdesktop.application.Application app) {
            super(app);

        }

        @Override
        protected Object doInBackground() {
            String openSCPath = "";
            Object obj = cbRutaOpenSC.getSelectedItem();
            if (obj instanceof Par) {
                openSCPath = ((Par) obj).getB().toString();
            } else {
                openSCPath = obj.toString();
            }
            Configuracion.setOpenSCPath(openSCPath);
            boolean dniEnabled = cbDNIeLocal.isSelected();
            Configuracion.setDNIeAccessEnabled(dniEnabled);
            boolean globalDniEnabled = cbDNIeGlobal.isSelected();
            Configuracion.setGlobalDNIeAccessEnabled(globalDniEnabled);
            int accesPolicy = cbSolicitarClave.getSelectedIndex();
            Configuracion.setDNIePassPolicy(accesPolicy);
            return null;
        }

        @Override
        protected void succeeded(Object result) {
            // Runs on the EDT.  Update the GUI based on
            // the result computed by doInBackground().
        }
    }
}
