/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
 **/
/*
 * PanelSelectorArchivo.java
 *
 * Created on 12-jul-2011, 9:25:24
 */
package com.codeko.apps.maimonides.swing;

import java.io.File;
import javax.swing.JFileChooser;
import org.jdesktop.application.Action;

/**
 *
 * @author Codeko <codeko@codeko.com>
 */
public class PanelSelectorArchivo extends javax.swing.JPanel {

    File currentDirectory = javax.swing.filechooser.FileSystemView.getFileSystemView().getDefaultDirectory();
    File selectedFile = null;
    int fileSelectionMode = JFileChooser.DIRECTORIES_ONLY;

    /** Creates new form PanelSelectorArchivo */
    public PanelSelectorArchivo() {
        initComponents();
    }

    public File getCurrentDirectory() {
        return currentDirectory;
    }

    public void setCurrentDirectory(File currentDirectory) {
        this.currentDirectory = currentDirectory;
    }

    public File getSelectedFile() {
        return selectedFile;
    }

    public void setSelectedFile(File selectedFile) {
        this.selectedFile = selectedFile;
        if (selectedFile == null) {
            tfFile.setText("");
        } else {
            tfFile.setText(selectedFile.getAbsolutePath());
        }
    }

    public int getFileSelectionMode() {
        return fileSelectionMode;
    }

    public void setFileSelectionMode(int fileSelectionMode) {
        this.fileSelectionMode = fileSelectionMode;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfFile = new javax.swing.JTextField();
        bOpenFile = new javax.swing.JButton();

        tfFile.setEditable(false);
        tfFile.setName("tfFile"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(PanelSelectorArchivo.class, this);
        bOpenFile.setAction(actionMap.get("openFile")); // NOI18N
        bOpenFile.setName("bOpenFile"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tfFile, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bOpenFile))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bOpenFile))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void openFile() {
        JFileChooser jfc = new JFileChooser(getCurrentDirectory());
        jfc.setFileSelectionMode(getFileSelectionMode());
        int op = jfc.showOpenDialog(bOpenFile);
        if (op == JFileChooser.APPROVE_OPTION) {
            setSelectedFile(jfc.getSelectedFile());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOpenFile;
    private javax.swing.JTextField tfFile;
    // End of variables declaration//GEN-END:variables
}
