/**
 *  Maimónides, gestión para centros escolares.
 *  Copyright Codeko and individual contributors
 *  as indicated by the @author tags.
 * 
 *  This is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as
 *  published by the Free Software Foundation; either version 2 of
 *  the License, or (at your option) any later version.
 * 
 *  This software is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 *  General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public
 *  License along with this software; if not, write to the Free
 *  Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 *  02110-1301 USA, or see the FSF site: http://www.fsf.org.
 *  
 *  For more information:
 *  maimonides@codeko.com
 *  http://codeko.com/maimonides
**/


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCargable.java
 *
 * Created on 28-may-2009, 17:39:26
 */
package com.codeko.apps.maimonides;

import java.awt.Component;
import javax.swing.JComponent;

/**
 *
 * @author Codeko
 */
public class PanelCargable extends javax.swing.JPanel implements ICargable {

    boolean cargado = false;

    /** Creates new form PanelCargable */
    public PanelCargable() {
        initComponents();
    }

    private void operarComponentes(JComponent comp, boolean cargar) {
        for (Component c : comp.getComponents()) {
            if (c instanceof ICargable) {
                if (cargar) {
                    ((ICargable) c).cargar();
                } else {
                    ((ICargable) c).vaciar();
                }
            }
            if (c instanceof JComponent) {
                operarComponentes((JComponent) c, cargar);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void cargar() {
        if (!isCargado()) {
            operarComponentes(this, true);
            setCargado(true);
        }
    }

    @Override
    public void vaciar() {
        operarComponentes(this, false);
        setCargado(false);
    }

    @Override
    public boolean isCargado() {
        return this.cargado;
    }

    @Override
    public void setCargado(boolean cargado) {
        this.cargado = cargado;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
